---
- name: requirment for ansible mysql python
  apt: name={{item}} state=installed
  with_items:
        - mysql-server-5.6
        - mysql-client-5.6
        - python-pip
        - libmysqlclient-dev
        - python-dev
  tags: ['mysql']

- name: install mysql python
  pip: name=MySQL-python
  tags: ['mysql']

- name: start MySQL server
  shell: service mysql start
  tags: ['mysql']

- name: Update MySQL root password for all root accounts
  mysql_user: name=root host={{ item }} password=$4curepa$s state=present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  tags: ['mysql']

- name: Copy the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=~/.my.cnf mode=0600
  tags: ['mysql']

- name: Ensure Anonymous user(s) are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
  tags: ['mysql']

- name: Remove the test database
  mysql_db: name=test state=absent
  tags: ['mysql']

- name: copy telegram bot schema
  template:
    src: schema.sql
    dest: /tmp/schema.sql
  tags: ['mysql']

- name: create telegram bot database
  mysql_db: name=telegrambot state=present target=/tmp/schema.sql
  tags: ['mysql']

- name: create mysql user
  mysql_user: name=bot password=$4curepa$s priv=telegrambot.*:ALL state=present
  tags: ['mysql']
